#ifndef __BD_REG_DEF_H__
#define __BD_REG_DEF_H__

// bd reg id defines
#define BD_ID_DES_CMD_SHORT                       {0, 1}
#define BD_ID_DES_OP_CODE                         {1, 16}
#define BD_ID_DES_CMD_ID_DEP                      {17, 20}
#define BD_ID_DEP_ID_EN                           {37, 1}
                                        //reserve {34, 7}
#define BD_ID_DES_TSK_TYP                         {41, 4}
#define BD_ID_DES_TSK_EU_TYP                      {45, 5}
#define BD_ID_DES_OPT_RQ                          {50, 1}
#define BD_ID_DES_TSK_OPD_NUM                     {51, 2}
#define BD_ID_DES_PAD_MODE                        {53, 2}
#define BD_ID_DES_OPT_RES0_SIGN                   {55, 1}
#define BD_ID_DES_RSVD0                           {56, 3}
#define BD_ID_DES_PWR_STEP                        {59, 4}
#define BD_ID_DES_INTR_EN                         {63, 1}
#define BD_ID_DES_MSG_ID                          {64, 9}
#define BD_ID_DES_OPT_RES_ADD                     {64, 1}
#define BD_ID_DES_OPT_RELU                        {65, 1}
#define BD_ID_DES_OPT_LEFT_TRAN                   {66, 1}
#define BD_ID_DES_OPT_OPD4_CONST                  {67, 1}
#define BD_ID_DES_OPT_KERNEL_ROTATE               {68, 1}
#define BD_ID_DES_OPT_OPD0_SIGN                   {69, 1}
#define BD_ID_DES_OPT_OPD1_SIGN                   {70, 1}
#define BD_ID_DES_OPT_OPD2_SIGN                   {71, 1}
#define BD_ID_DES_OPT_RES0_PREC                   {72, 3}
#define BD_ID_DES_OPT_OPD0_PREC                   {75, 3}
#define BD_ID_DES_OPT_OPD1_PREC                   {78, 3}
#define BD_ID_DES_MSG_CNT                         {80, 8}
#define BD_ID_DES_OPT_OPD2_PREC                   {81, 3}
#define BD_ID_DES_OPT_OPD0_CONST                  {84, 1}
#define BD_ID_DES_OPT_OPD1_CONST                  {85, 1}
#define BD_ID_DES_OPT_OPD2_CONST                  {86, 1}
#define BD_ID_DES_SHORT_RES0_STR                  {87, 3}
#define BD_ID_DES_SHORT_OPD0_STR                  {90, 3}
#define BD_ID_DES_SHORT_OPD1_STR                  {93, 3}
#define BD_ID_DES_SHORT_OPD2_STR                  {96, 3}
#define BD_ID_DES_OPT_RES_ADD_SIGN                {99, 1}
#define BD_ID_DES_RSVD2                           {100, 25}
#define BD_ID_DES_SYM_RANGE                       {125, 1}
#define BD_ID_DES_OPT_OPD3_CONST                  {126, 1}
#define BD_ID_DES_OPT_OPD5_CONST                  {127, 1}
#define BD_ID_DES_OPD0_X_INS0                     {128, 4}
#define BD_ID_DES_OPD0_Y_INS0                     {132, 4}
#define BD_ID_DES_OPD1_X_INS0                     {136, 4}
#define BD_ID_DES_OPD1_Y_INS0                     {140, 4}
#define BD_ID_DES_OPD0_UP_PAD                     {144, 4}
#define BD_ID_DES_OPD0_DN_PAD                     {148, 4}
#define BD_ID_DES_OPD0_LF_PAD                     {152, 4}
#define BD_ID_DES_OPD0_RT_PAD                     {156, 4}
#define BD_ID_DES_RES_OP_X_STR                    {160, 4}
#define BD_ID_DES_RES_OP_Y_STR                    {164, 4}
#define BD_ID_DES_RES0_H_SHIFT                    {168, 4}
#define BD_ID_DES_RES0_W_SHIFT                    {172, 4}
#define BD_ID_DES_OPD0_H_SHIFT                    {176, 4}
#define BD_ID_DES_OPD0_W_SHIFT                    {180, 4}
#define BD_ID_DES_OPD1_H_SHIFT                    {184, 4}
#define BD_ID_DES_OPD1_W_SHIFT                    {188, 4}
#define BD_ID_DES_TSK_LANE_NUM                    {192, 64}
#define BD_ID_DES_RES0_N                          {256, 16}
#define BD_ID_DES_RES0_C                          {272, 16}
#define BD_ID_DES_RES0_H                          {288, 16}
#define BD_ID_DES_RES0_W                          {304, 16}
#define BD_ID_DES_OPD0_N                          {320, 16}
#define BD_ID_DES_OPD0_C                          {336, 16}
#define BD_ID_DES_OPD0_H                          {352, 16}
#define BD_ID_DES_OPD0_W                          {368, 16}
#define BD_ID_DES_OPD1_N                          {384, 16}
#define BD_ID_DES_OPD1_C                          {400, 16}
#define BD_ID_DES_OPD1_H                          {416, 16}
#define BD_ID_DES_OPD1_W                          {432, 16}
#define BD_ID_DES_RES0_N_STR                      {448, 16}
#define BD_ID_DES_RES0_C_STR                      {464, 16}
#define BD_ID_DES_OPD0_N_STR                      {480, 16}
#define BD_ID_DES_OPD0_C_STR                      {496, 16}
#define BD_ID_DES_OPD1_N_STR                      {512, 16}
#define BD_ID_DES_OPD1_C_STR                      {528, 16}
#define BD_ID_DES_OPD2_N_STR                      {544, 16}
#define BD_ID_DES_OPD2_C_STR                      {560, 16}
#define BD_ID_DES_RES0_ADDR                       {576, 32}
#define BD_ID_DES_OPD0_ADDR                       {608, 32}
#define BD_ID_DES_OPD1_ADDR                       {640, 32}
#define BD_ID_DES_OPD2_ADDR                       {672, 32}
#define BD_ID_DES_RES0_H_STR                      {704, 32}
#define BD_ID_DES_RES0_W_STR                      {736, 32}
#define BD_ID_DES_OPD0_H_STR                      {768, 32}
#define BD_ID_DES_OPD0_W_STR                      {800, 32}
#define BD_ID_DES_OPD1_H_STR                      {832, 32}
#define BD_ID_DES_OPD1_W_STR                      {864, 32}
#define BD_ID_DES_OPD2_H_STR                      {896, 32}
#define BD_ID_DES_OPD2_W_STR                      {928, 32}
#define BD_ID_DES_RES1_ADDR                       {960, 32}
#define BD_ID_DES_OPD3_ADDR                       {992, 32}

// control reg defines
#define BD_ID_CFG_CURRENT_CMD_ID                  {224, 32}
#define BD_ID_CFG_FB_PXL_EN                       {29, 1}
#define BD_ID_CFG_IST_FIFO_DEPTH                  {32, 9}
#define BD_ID_CFG_DES_MODE                        {54, 2}
#define BD_ID_CFG_CMD_ID_RESET                    {63, 1}
#define BD_ID_CFG_SEED_INITIAL_L32                {256, 32}
#define BD_ID_CFG_SEED_INITIAL_H32                {288, 32}
#define BD_ID_CFG_BASE_MSGID                      {672, 9}
#define BD_ID_CFG_DBG_MODE                        {768, 2}
#define BD_ID_CFG_DBG_EXEC                        {784, 1}
#define BD_ID_IRQ_DBG_SINGLE_STEP_STAT            {800, 1}
#define BD_ID_IRQ_DBG_BREAKPOINT_STAT             {801, 1}
#define BD_ID_CFG_EU_CLK_GATE_EN                  {1004, 1}
#define BD_ID_CFG_CUBE_CLK_GATE_EN                {1005, 1}
#define BD_ID_CFG_LMEM_CLK_GATE_EN                {1006, 1}
#define BD_ID_CFG_POWER_CTL                       {1536, 32}

// bd pack defines
#define BD_PACK_DES_CMD_SHORT(val)                {BD_ID_DES_CMD_SHORT, (val)}
#define BD_PACK_DES_OP_CODE(val)                  {BD_ID_DES_OP_CODE, (val)}
#define BD_PACK_DES_CMD_ID_DEP(val)               {BD_ID_DES_CMD_ID_DEP, (val)}
#define BD_PACK_DES_TSK_TYP(val)                  {BD_ID_DES_TSK_TYP, (val)}
#define BD_PACK_DES_TSK_EU_TYP(val)               {BD_ID_DES_TSK_EU_TYP, (val)}
#define BD_PACK_DES_OPT_RQ(val)                   {BD_ID_DES_OPT_RQ, (val)}
#define BD_PACK_DES_TSK_OPD_NUM(val)              {BD_ID_DES_TSK_OPD_NUM, (val)}
#define BD_PACK_DES_PAD_MODE(val)                 {BD_ID_DES_PAD_MODE, (val)}
#define BD_PACK_DES_OPT_RES0_SIGN(val)            {BD_ID_DES_OPT_RES0_SIGN, (val)}
#define BD_PACK_DES_RSVD0(val)                    {BD_ID_DES_RSVD0, (val)}
#define BD_PACK_DES_PWR_STEP(val)                 {BD_ID_DES_PWR_STEP, (val)}
#define BD_PACK_DES_INTR_EN(val)                  {BD_ID_DES_INTR_EN, (val)}
#define BD_PACK_DES_OPT_RES_ADD(val)              {BD_ID_DES_OPT_RES_ADD, (val)}
#define BD_PACK_DES_OPT_RELU(val)                 {BD_ID_DES_OPT_RELU, (val)}
#define BD_PACK_DES_OPT_LEFT_TRAN(val)            {BD_ID_DES_OPT_LEFT_TRAN, (val)}
#define BD_PACK_DES_OPT_OPD4_CONST(val)           {BD_ID_DES_OPT_OPD4_CONST, (val)}
#define BD_PACK_DES_OPT_KERNEL_ROTATE(val)        {BD_ID_DES_OPT_KERNEL_ROTATE, (val)}
#define BD_PACK_DES_OPT_OPD0_SIGN(val)            {BD_ID_DES_OPT_OPD0_SIGN, (val)}
#define BD_PACK_DES_OPT_OPD1_SIGN(val)            {BD_ID_DES_OPT_OPD1_SIGN, (val)}
#define BD_PACK_DES_OPT_OPD2_SIGN(val)            {BD_ID_DES_OPT_OPD2_SIGN, (val)}
#define BD_PACK_DES_OPT_RES0_PREC(val)            {BD_ID_DES_OPT_RES0_PREC, (val)}
#define BD_PACK_DES_OPT_OPD0_PREC(val)            {BD_ID_DES_OPT_OPD0_PREC, (val)}
#define BD_PACK_DES_OPT_OPD1_PREC(val)            {BD_ID_DES_OPT_OPD1_PREC, (val)}
#define BD_PACK_DES_OPT_OPD2_PREC(val)            {BD_ID_DES_OPT_OPD2_PREC, (val)}
#define BD_PACK_DES_OPT_OPD0_CONST(val)           {BD_ID_DES_OPT_OPD0_CONST, (val)}
#define BD_PACK_DES_OPT_OPD1_CONST(val)           {BD_ID_DES_OPT_OPD1_CONST, (val)}
#define BD_PACK_DES_OPT_OPD2_CONST(val)           {BD_ID_DES_OPT_OPD2_CONST, (val)}
#define BD_PACK_DES_SHORT_RES0_STR(val)           {BD_ID_DES_SHORT_RES0_STR, (val)}
#define BD_PACK_DES_SHORT_OPD0_STR(val)           {BD_ID_DES_SHORT_OPD0_STR, (val)}
#define BD_PACK_DES_SHORT_OPD1_STR(val)           {BD_ID_DES_SHORT_OPD1_STR, (val)}
#define BD_PACK_DES_SHORT_OPD2_STR(val)           {BD_ID_DES_SHORT_OPD2_STR, (val)}
#define BD_PACK_DES_OPT_RES_ADD_SIGN(val)         {BD_ID_DES_OPT_RES_ADD_SIGN, (val)}
#define BD_PACK_DES_RSVD2(val)                    {BD_ID_DES_RSVD2, (val)}
#define BD_PACK_DES_SYM_RANGE(val)                {BD_ID_DES_SYM_RANGE, (val)}
#define BD_PACK_DES_OPT_OPD3_CONST(val)           {BD_ID_DES_OPT_OPD3_CONST, (val)}
#define BD_PACK_DES_OPT_OPD5_CONST(val)           {BD_ID_DES_OPT_OPD5_CONST, (val)}
#define BD_PACK_DES_OPD0_X_INS0(val)              {BD_ID_DES_OPD0_X_INS0, (val)}
#define BD_PACK_DES_OPD0_Y_INS0(val)              {BD_ID_DES_OPD0_Y_INS0, (val)}
#define BD_PACK_DES_OPD1_X_INS0(val)              {BD_ID_DES_OPD1_X_INS0, (val)}
#define BD_PACK_DES_OPD1_Y_INS0(val)              {BD_ID_DES_OPD1_Y_INS0, (val)}
#define BD_PACK_DES_OPD0_UP_PAD(val)              {BD_ID_DES_OPD0_UP_PAD, (val)}
#define BD_PACK_DES_OPD0_DN_PAD(val)              {BD_ID_DES_OPD0_DN_PAD, (val)}
#define BD_PACK_DES_OPD0_LF_PAD(val)              {BD_ID_DES_OPD0_LF_PAD, (val)}
#define BD_PACK_DES_OPD0_RT_PAD(val)              {BD_ID_DES_OPD0_RT_PAD, (val)}
#define BD_PACK_DES_RES_OP_X_STR(val)             {BD_ID_DES_RES_OP_X_STR, (val)}
#define BD_PACK_DES_RES_OP_Y_STR(val)             {BD_ID_DES_RES_OP_Y_STR, (val)}
#define BD_PACK_DES_RES0_H_SHIFT(val)             {BD_ID_DES_RES0_H_SHIFT, (val)}
#define BD_PACK_DES_RES0_W_SHIFT(val)             {BD_ID_DES_RES0_W_SHIFT, (val)}
#define BD_PACK_DES_OPD0_H_SHIFT(val)             {BD_ID_DES_OPD0_H_SHIFT, (val)}
#define BD_PACK_DES_OPD0_W_SHIFT(val)             {BD_ID_DES_OPD0_W_SHIFT, (val)}
#define BD_PACK_DES_OPD1_H_SHIFT(val)             {BD_ID_DES_OPD1_H_SHIFT, (val)}
#define BD_PACK_DES_OPD1_W_SHIFT(val)             {BD_ID_DES_OPD1_W_SHIFT, (val)}
#define BD_PACK_DES_TSK_LANE_NUM(val)             {BD_ID_DES_TSK_LANE_NUM, (val)}
#define BD_PACK_DES_RES0_N(val)                   {BD_ID_DES_RES0_N, (val)}
#define BD_PACK_DES_RES0_C(val)                   {BD_ID_DES_RES0_C, (val)}
#define BD_PACK_DES_RES0_H(val)                   {BD_ID_DES_RES0_H, (val)}
#define BD_PACK_DES_RES0_W(val)                   {BD_ID_DES_RES0_W, (val)}
#define BD_PACK_DES_OPD0_N(val)                   {BD_ID_DES_OPD0_N, (val)}
#define BD_PACK_DES_OPD0_C(val)                   {BD_ID_DES_OPD0_C, (val)}
#define BD_PACK_DES_OPD0_H(val)                   {BD_ID_DES_OPD0_H, (val)}
#define BD_PACK_DES_OPD0_W(val)                   {BD_ID_DES_OPD0_W, (val)}
#define BD_PACK_DES_OPD1_N(val)                   {BD_ID_DES_OPD1_N, (val)}
#define BD_PACK_DES_OPD1_C(val)                   {BD_ID_DES_OPD1_C, (val)}
#define BD_PACK_DES_OPD1_H(val)                   {BD_ID_DES_OPD1_H, (val)}
#define BD_PACK_DES_OPD1_W(val)                   {BD_ID_DES_OPD1_W, (val)}
#define BD_PACK_DES_RES0_N_STR(val)               {BD_ID_DES_RES0_N_STR, (val)}
#define BD_PACK_DES_RES0_C_STR(val)               {BD_ID_DES_RES0_C_STR, (val)}
#define BD_PACK_DES_OPD0_N_STR(val)               {BD_ID_DES_OPD0_N_STR, (val)}
#define BD_PACK_DES_OPD0_C_STR(val)               {BD_ID_DES_OPD0_C_STR, (val)}
#define BD_PACK_DES_OPD1_N_STR(val)               {BD_ID_DES_OPD1_N_STR, (val)}
#define BD_PACK_DES_OPD1_C_STR(val)               {BD_ID_DES_OPD1_C_STR, (val)}
#define BD_PACK_DES_OPD2_N_STR(val)               {BD_ID_DES_OPD2_N_STR, (val)}
#define BD_PACK_DES_OPD2_C_STR(val)               {BD_ID_DES_OPD2_C_STR, (val)}
#define BD_PACK_DES_RES0_ADDR(val)                {BD_ID_DES_RES0_ADDR, (val)}
#define BD_PACK_DES_OPD0_ADDR(val)                {BD_ID_DES_OPD0_ADDR, (val)}
#define BD_PACK_DES_OPD1_ADDR(val)                {BD_ID_DES_OPD1_ADDR, (val)}
#define BD_PACK_DES_OPD2_ADDR(val)                {BD_ID_DES_OPD2_ADDR, (val)}
#define BD_PACK_DES_RES0_H_STR(val)               {BD_ID_DES_RES0_H_STR, (val)}
#define BD_PACK_DES_RES0_W_STR(val)               {BD_ID_DES_RES0_W_STR, (val)}
#define BD_PACK_DES_OPD0_H_STR(val)               {BD_ID_DES_OPD0_H_STR, (val)}
#define BD_PACK_DES_OPD0_W_STR(val)               {BD_ID_DES_OPD0_W_STR, (val)}
#define BD_PACK_DES_OPD1_H_STR(val)               {BD_ID_DES_OPD1_H_STR, (val)}
#define BD_PACK_DES_OPD1_W_STR(val)               {BD_ID_DES_OPD1_W_STR, (val)}
#define BD_PACK_DES_OPD2_H_STR(val)               {BD_ID_DES_OPD2_H_STR, (val)}
#define BD_PACK_DES_OPD2_W_STR(val)               {BD_ID_DES_OPD2_W_STR, (val)}
#define BD_PACK_DES_RES1_ADDR(val)                {BD_ID_DES_RES1_ADDR, (val)}
#define BD_PACK_DES_OPD3_ADDR(val)                {BD_ID_DES_OPD3_ADDR, (val)}


#endif  // __BD_REG_DEF_H__
